### PR TITLE
Fixed DeeplabV3 training example

### PR DESCRIPTION
**Pull request by tersekmatija**
Removed the old example. Created a new example for training DeeplabV3 with MobileNetV2 backbone. Updated README and added link to experiment where you can test the trained model.
Experiment PR: https://github.com/luxonis/depthai-experiments/pull/183

### CODE REVIEW

**Review by Erol444 — CHANGES_REQUESTED** [review]
Add blobconverter to convert from IR into blob, use 2020.2 version (the only supported one)

**Comment by franva** [comment]
> Add blobconverter to convert from IR into blob, use 2020.2 version (the only supported one)

@tersekmatija  and @Erol444 , AWESOME response time and great work~!!! 

I will try this notebook out and provide feedback if I found anything for improvement.

Just one question, I thought the latest version that DepthAI supports for blobconverter is 2021.4?
Coz I saw the `2021.4` on your official website: http://blobconverter.luxonis.com/

**Comment by Erol444** [comment]
@franva please do! I quickly went through training and it works as expected with the experiment code @tersekmatija  provided. The conversion process fails with newer versions of openvino, that's why we use an old one. DepthAI version 2.8 and newer actually removed support for openvino version 2020.1/2020.2 that's why the experiment requirement is depthai==2.7.0.0. We will look into converting with the newer openvino version in the future. Thanks:)

**Comment by Luxonis-Brandon** [comment]
Thanks @tersekmatija and all! !

**Comment by franva** [comment]
hi @Erol444  and @tersekmatija 

I have had a try with the training notebook, it did give me a model and converted it to a `.blob` file, but when using that blob file back in `depthai` project, it generates errors.

You can find more details here:
https://github.com/luxonis/depthai-ml-training/issues/13

Generally speaking, I feel that in order to use the trained model, we have to downgrade the version, this is not a good approach. Users will soon find very confusing switching between different versions.

**Pull request merged**
