### PR TITLE
[Proposal] Structure Refactor

### PR DESCRIPTION
**Pull request by HonzaCuhel**
This PR proposes a structure refactor for the DepthAI ML Training repository.

The proposing structure looks following:

- Each of our library (`DataDreamer`, `LuxonisTrain`, and `ModelConverter`) has its own subfolder in the root folder of the repo, where each subfolder contains a `README.md` shortly introducing the given library, linking the user to its source repository and to the documentation and describing all the available tutorials.
- All the current and future tutorials not utilizing our libraries (e.g. training YOLO11 instance segmentation model) are moved to the `others` subfolder, where there will be further divided into folders based on their task they are solving (e.g. `image-classification`, `object-detection`, `semantic-segmentation`).

Here's an example:
```
    depthai-ml-training/
    ├── datadreamer/                    - Folder with tutorials featuring DataDreamer
    │   ├── ...
    │   └── README.md                   - Short description of the DataDreamer and and links to github repository, documentation and all tutorials
    ├── luxonis-train/                  - Folder with tutorials featuring LuxonisTrain
    │   ├── ...
    │   └── README.md                   - Short description of the LuxonisTrain and and links to github repository, documentation and all tutorials
    ├── modelconverter/                 - Folder with tutorials featuring ModelConverter
    │   ├── ...
    │   └── README.md                   - Short description of the ModelConverter and links to github repository, documentation and all tutorials
    ├── others/                         - Folder containing tutorials that aren't featuring any Luxonis library
    │   ├── image-classification/       - Folder for all image classification training tutorials
    │   ├── object-detection/           - Folder for all object detection training tutorials (YOLO)
    │   ├── semantic-segmentation/      - Folder for all semantic segmentation training tutorials
    │   └── README.md                   - Short description of all available tutorials
    ├── LICENSE 
    └── README.md                       - Description of the whole repository structure, introducing key libraries and terms, etc.
```

Final note: the source branch reflects the initial changed of the proposal.

### CODE REVIEW

**Comment by HonzaCuhel** [comment]
I was also thinking that maybe it'd be nice to also link in the repository the `luxonis-ml` examples from [here](https://github.com/luxonis/luxonis-ml/tree/main/examples). I'm aware that they are not about training a model, but IMO this would be a great place to offer the users these additional examples.

**Comment by tersekmatija** [comment]
Thanks, do we have enough library-specific tutorials to separate?

In other words, should datadreamer be featured separately, or can it rather be featured as part of some dedicated training tutorial?
If we deem separate is necessary, I'm OK with this, but perhaps we user more user friendly naming (luxonis-train -> training, modelconverter -> conversion, ...).

**Comment by tersekmatija** [comment]
Another note, it might make sense to push this to main, then update any links we have in documentation to link there, and lastly make main branch the default one?

**Comment by HonzaCuhel** [comment]
> Thanks, do we have enough library-specific tutorials to separate?

For DataDreamer together with LuxonisTrain we have 2 in preparation. Apart from that we have 3 more tutorials featuring DataDreamer and training a YOLOv8 model, where  Otherwise, for LuxonisTrain I know about additional 1. For ModelConverter I don't know how many are planned.

> In other words, should datadreamer be featured separately, or can it rather be featured as part of some dedicated training tutorial? If we deem separate is necessary, I'm OK with this, but perhaps we user more user friendly naming (luxonis-train -> training, modelconverter -> conversion, ...).

Yeah, perhaps dividing it into 2 folder could be better. If necessary we could further divide it there between tutorials featuring DataDreamer and not.

**Comment by HonzaCuhel** [comment]
> Another note, it might make sense to push this to main, then update any links we have in documentation to link there, and lastly make main branch the default one?

I agree, but shouldn't we first agree on the structure through PR before pushing it to the main branch?

**Comment by HonzaCuhel** [comment]
Closing this PR in favor of this [new](https://github.com/luxonis/depthai-ml-training/pull/65) one from the `main` branch.

**Pull request closed without merging**
