### PR TITLE
Fix YoloV3/YoloV4 demos

### PR DESCRIPTION
**Pull request by Erol444**
Changed the openvino version to 2021.1. Showcased how to use the blob in gen2 (by modifying 22_1_tiny_yolo_v3 demo/22_2_tiny_yolo_v4).

### CODE REVIEW

**Comment by Erol444** [comment]
Note: when we merge develop->main on `depthai-python`, we will break a link to the docs inside the notebook (currently the link is `22_tiny_yolo_v3`, will be `22_1_tiny_yolo_v3`)

**Comment by Luxonis-Brandon** [comment]
Are we good to merge this @Erol444 ?  Was just about to link to it in an email asking about training.

**Comment by Erol444** [comment]
@Luxonis-Brandon: @cafemoloko will re-check everything and we can merge it if everything is ok

**Review by cafemoloko — CHANGES_REQUESTED** [review]
The notebook runs ok, however, I've noticed minor issues when downloading a model.

One but last cell: file `fine_tuned_model.tar` is in folder `content`, not `content/models/research/fine_tuned_model`. Executing cell gives following message:
```
tar: fine_tuned_model: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
```
Last cell: 
`files.download("fine_tuned_model.tar.gz")` - no such file.
Changing the line to: `files.download("fine_tuned_model.tar")` allows to download a file without errors.

**Comment by cafemoloko** [comment]
I've commented this notebook: `Easy_TinyYOLOv3_Object_Detector_Training_on_Custom_Data.ipynb`

```

**Pull request merged**
